# Lock-In Focus Monitor - Relaxed Mode Configuration
# Use for casual work or when you need occasional breaks

model:
  architecture: "mobilenet_v3_small"
  input_size: 224
  num_classes: 5
  model_path: "models/distraction_classifier.pt"
  use_gpu: true

classes:
  - "focused"
  - "looking_away"
  - "using_phone"
  - "yawning"
  - "sleepy"

distracted_classes:
  - "looking_away"
  - "using_phone"
  - "yawning"
  - "sleepy"

inference:
  frame_interval_seconds: 5  # Less frequent checks
  camera_index: 0
  max_inference_time_ms: 300

scoring:
  rolling_window_size: 15  # Longer window for smoother scoring
  alert_threshold: 0.2  # Lower threshold = more lenient
  consecutive_frames_required: 5  # More frames needed before alert

notification:
  enabled: true
  title: "Lock-In Monitor"
  distracted_message: "Gentle reminder: You might want to refocus when ready."
  cooldown_seconds: 120  # Longer cooldown = less frequent alerts

logging:
  database_path: "data/focus_log.db"
  log_predictions: true
  log_scores: true
  csv_backup: true
  csv_path: "data/focus_log.csv"

training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  validation_split: 0.2
  early_stopping_patience: 10
  checkpoint_dir: "checkpoints"

