# Lock-In Focus Monitor - Strict Mode Configuration
# Use for deep focus work sessions where you need maximum accountability

model:
  architecture: "mobilenet_v3_small"
  input_size: 224
  num_classes: 5
  model_path: "models/distraction_classifier.pt"
  use_gpu: true

classes:
  - "focused"
  - "looking_away"
  - "using_phone"
  - "yawning"
  - "sleepy"

distracted_classes:
  - "looking_away"
  - "using_phone"
  - "yawning"
  - "sleepy"

inference:
  frame_interval_seconds: 2  # More frequent checks
  camera_index: 0
  max_inference_time_ms: 300

scoring:
  rolling_window_size: 8  # Shorter window for faster response
  alert_threshold: 0.5  # Higher threshold = stricter
  consecutive_frames_required: 2  # Quick alert trigger

notification:
  enabled: true
  title: "Lock-In Monitor - STRICT MODE"
  distracted_message: "🚨 FOCUS LOST! Get back to work immediately!"
  cooldown_seconds: 30  # Shorter cooldown = more frequent alerts

logging:
  database_path: "data/focus_log.db"
  log_predictions: true
  log_scores: true
  csv_backup: true
  csv_path: "data/focus_log.csv"

training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  validation_split: 0.2
  early_stopping_patience: 10
  checkpoint_dir: "checkpoints"

